Question 1. Create a 3x3x3 array with random values

In [14]:
import numpy as np
mat1 = np.random.uniform((3,3,3))
print (mat1)

[1.25222809 1.9689827  2.76953973]


Question 2. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [15]:
mat1 = np.diag(1+np.arange(4), k = -1)
print (mat1)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


Question 3. Create a 8x8 matrix and fill it with a checkerboard pattern

In [16]:
mat1 = np.zeros ((8,8), dtype=int)
mat1[1::2, ::2]= 1
mat1[::2, 1::2] = 1
print (mat1)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Question 4. Normalize a 5x5 random matrix

In [21]:
mat1= np.random.random((5,5))
print("before normalization : ")
print(mat1)
print("\nafter normalization : " )
max1, min1 = mat1.max(), mat1.min()
mat1= (mat1-min1)/(max1-min1)
print (mat1)

before normalization : 
[[0.61398612 0.05387071 0.57863632 0.21038133 0.40998266]
 [0.10141562 0.07762809 0.27700977 0.50288477 0.61057995]
 [0.68960001 0.3129758  0.01374527 0.67744988 0.70058397]
 [0.3492171  0.30592674 0.01491697 0.19173258 0.40745327]
 [0.13852165 0.78290359 0.94149376 0.52868101 0.25647972]]

after normalization : 
[[0.64698661 0.04325035 0.60888383 0.21194975 0.4270957 ]
 [0.09449797 0.06885791 0.2837671  0.52723287 0.64331518]
 [0.72848919 0.32253411 0.         0.71539283 0.74032856]
 [0.36159782 0.31493608 0.00126295 0.19184867 0.42436933]
 [0.13449376 0.8290591  1.         0.55503808 0.26163821]]


Question 5. find common values between two arrays

In [22]:
Array1=np.array([1,2,3,4,5,6,7])
Array2=np.array([5,6,7,8,9,])
print(np.intersect1d(Array1,Array2))

[5 6 7]


Question 6. How to get the dates of yesterday, today and tomorrow?

In [23]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yesterday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yesterday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


Question 7. Consider two random array A and B, check if they are equal

In [24]:
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Checking whether the two arrays are equal")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[0 0 0 0 0 0]
Second array:
[1 0 1 1 1 0]
Checking whether the two arrays are equal
False


Question 8. Create random vector of size 10 and replace the maximum value by 0

In [25]:
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by -1:")
print(x)

Original array:
[0.96807859 0.52462604 0.7518897  0.65729214 0.86960589 0.96858436
 0.1359377  0.93733659 0.1635795  0.24878588]
Maximum value replaced by -1:
[0.96807859 0.52462604 0.7518897  0.65729214 0.86960589 0.
 0.1359377  0.93733659 0.1635795  0.24878588]


Question 9. How to print all the values of an array?

In [26]:
import sys
np.set_printoptions(threshold=sys.maxsize)
x = np.zeros((4, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Question 10.Subtract the mean of each row of a matrix

In [28]:
print("Original matrix:\n")
X = np.random.rand(2, 3)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.47037729 0.3626591  0.95153953]
 [0.47133193 0.93154327 0.94666758]]

Subtract the mean of each row of the said matrix:

[[-0.12448135 -0.23219954  0.35668089]
 [-0.31184899  0.14836234  0.16348665]]


Question 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [30]:

Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[6. 3. 3. 2. 3. 3. 1. 2. 3. 4.]


Question 12.How to get the diagonal of a dot product?

In [31]:
a = np.arange(15).reshape(5, 3)
b = np.arange(9).reshape(3, 3)

np.diag(np.dot(np.dot(a, b), a.T))

array([  60,  672, 1932, 3840, 6396])

Question 13 . How to find the most frequent value in an array?

In [32]:
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[3 7 4 8 4 5 5 4 3 4 3 6 2 5 5 7 4 3 5 7 3 5 3 9 5 3 4 6 0 6 3 1 6 9 3 6 9
 1 4 4]
Most frequent value in the above array:
3


14.How to get the n largest values of an array

In [33]:
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 4
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[6 7 8 9]


Question 15 . How to create a record array from a regular array?

In [36]:
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])

(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)
